# include .well-known folder for SSL certs
include: [".well-known"]

# Dependencies
#markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Sanchit Alekh
tagline:          Personal Webpage
description:      'Consultant Big Data Engineer at <a href="https://www.reply.com/data-reply/en/">Data Reply GmbH, Munich</a>'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Sanchit Alekh'
  url:            https://facebook.com/sanchitalekh

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/salekh

linkedin:
  url: https://www.linkedin.com/in/sanchitalekh/
