# Dependencies
#markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Sanchit Alekh
tagline:          'Personal Webpage'
description:      'Master Student of Computer Science at <a href="http://www.rwth-aachen.de/cms/~a/root/?lidx=1">RWTH Aachen University, Germany.</a>'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Sanchit Alekh'
  url:            https://facebook.com/sanchitalekh

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/salekh
