# include .well-known folder for SSL certs
include: [".well-known"]

# Additional Plugins
plugins: ["jekyll-paginate"]

# Dependencies
#markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Hosting
host:             0.0.0.0
port:             4000

# Setup
title:            Sanchit Alekh
tagline:          Personal Webpage
description:      'Data Engineer at <a href="https://www.rubinstein-schmiedel.com/">Rubinstein and Schmiedel AG, Munich</a>'
url:              http://sanchitalekh.in
baseurl:          /

author:
  name:           'Sanchit Alekh'
  url:            https://facebook.com/sanchitalekh

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/salekh

linkedin:
  url: https://www.linkedin.com/in/sanchitalekh/
