import { Share2 } from "lucide-react";
import ReactMarkdown from "react-markdown";

export function AIOverview({ summary }: { summary: string }) {
    if (!summary) return null;

    return (
        <div className="relative overflow-hidden rounded-2xl p-[1px] my-8 animate-in fade-in slide-in-from-bottom-4 duration-700">
            {/* Gradient Border */}
            <div className="absolute inset-0 bg-gradient-to-r from-blue-500 via-purple-500 to-pink-500 rounded-2xl opacity-75" />

            {/* Content Container */}
            <div className="relative bg-[var(--background)] rounded-2xl p-6 sm:p-8 border-none">
                {/* Header */}
                <div className="flex items-center gap-2 mb-4">
                    <div className="flex items-center justify-center w-8 h-8 rounded-full bg-gradient-to-tr from-blue-100 to-purple-100 dark:from-blue-900/30 dark:to-purple-900/30">
                        <svg className="w-5 h-5 text-indigo-500" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M12 2L14.8 9.2L22 12L14.8 14.8L12 22L9.2 14.8L2 12L9.2 9.2L12 2Z" fill="url(#sparkle-gradient)" />
                            <defs>
                                <linearGradient id="sparkle-gradient" x1="2" y1="2" x2="22" y2="22" gradientUnits="userSpaceOnUse">
                                    <stop stopColor="#3B82F6" />
                                    <stop offset="1" stopColor="#A855F7" />
                                </linearGradient>
                            </defs>
                        </svg>
                    </div>
                    <span className="text-lg font-semibold bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 bg-clip-text text-transparent">
                        AI Overview
                    </span>
                </div>

                {/* Summary */}
                <div className="prose prose-zinc dark:prose-invert max-w-none prose-p:leading-relaxed prose-lg">
                    <ReactMarkdown>{summary}</ReactMarkdown>
                </div>

                {/* Footer */}
                <div className="flex items-center justify-between mt-6 pt-4 border-t border-[var(--foreground)]/5">
                    <span className="text-xs font-medium text-[var(--foreground)]/50 flex items-center gap-1.5">
                        <svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                            <path d="M21 12a9 9 0 1 1-6.219-8.56" />
                        </svg>
                        Generated by Gemini 3 Pro
                    </span>
                    <div className="flex gap-3">
                        {/* Placeholder for actions like like/dislike/share if needed */}
                    </div>
                </div>
            </div>
        </div>
    );
}
